In [ ]:
inflected="Write Writing Writes Written ride riding rides rides run runner runs running code coder coding codes universe universal university universities change changes changing"

In [ ]:
words=inflected.split()

In [ ]:
words

['Write',
 'Writing',
 'Writes',
 'Written',
 'ride',
 'riding',
 'rides',
 'rides',
 'run',
 'runner',
 'runs',
 'running',
 'code',
 'coder',
 'coding',
 'codes',
 'universe',
 'universal',
 'university',
 'universities',
 'chage',
 'changes',
 'changing']

## porter stemmer

In [ ]:
import nltk

In [ ]:
from nltk.stem import PorterStemmer

In [ ]:
pstem=PorterStemmer()

In [ ]:
len(words)

23

In [ ]:
import time

In [ ]:
for w in words:
    print("Original :",w)
    print("porter :",pstem.stem(w))
    print("--------")
    print()
    time.sleep(1)

Original : Write
porter : write
--------

Original : Writing
porter : write
--------

Original : Writes
porter : write
--------

Original : Written
porter : written
--------

Original : ride
porter : ride
--------

Original : riding
porter : ride
--------

Original : rides
porter : ride
--------

Original : rides
porter : ride
--------

Original : run
porter : run
--------

Original : runner
porter : runner
--------

Original : runs
porter : run
--------

Original : running
porter : run
--------

Original : code
porter : code
--------

Original : coder
porter : coder
--------

Original : coding
porter : code
--------

Original : codes
porter : code
--------

Original : universe
porter : univers
--------

Original : universal
porter : univers
--------

Original : university
porter : univers
--------

Original : universities
porter : univers
--------

Original : chage
porter : chage
--------

Original : changes
porter : chang
--------

Original : changing
porter : chang
--------



## Snow Ball Stemmer

In [ ]:
from nltk.stem import SnowballStemmer

In [ ]:
snow_stemmer=SnowballStemmer(language="english")

In [ ]:
snow_stemmer

In [ ]:
snow_stemmer.stem("working")

'work'

In [ ]:
len(words)

23

In [ ]:
for w in words:
    print("Original :",w)
    print("porter :",pstem.stem(w))
    print("Snowball :",snow_stemmer.stem(w))
    print("-----------------")
    print()
    time.sleep(1)

Original : Write
porter : write
Snowball : write
-----------------

Original : Writing
porter : write
Snowball : write
-----------------

Original : Writes
porter : write
Snowball : write
-----------------

Original : Written
porter : written
Snowball : written
-----------------

Original : ride
porter : ride
Snowball : ride
-----------------

Original : riding
porter : ride
Snowball : ride
-----------------

Original : rides
porter : ride
Snowball : ride
-----------------

Original : rides
porter : ride
Snowball : ride
-----------------

Original : run
porter : run
Snowball : run
-----------------

Original : runner
porter : runner
Snowball : runner
-----------------

Original : runs
porter : run
Snowball : run
-----------------

Original : running
porter : run
Snowball : run
-----------------

Original : code
porter : code
Snowball : code
-----------------

Original : coder
porter : coder
Snowball : coder
-----------------

Original : coding
porter : code
Snowball : code
------------

## Lancaster stemmer

In [ ]:
from nltk.stem import LancasterStemmer

In [ ]:
lan=LancasterStemmer()

In [ ]:
lan.stem("writes")

'writ'

In [ ]:
for w in words:
    print("Original :",w)
    print("porter :",pstem.stem(w))
    print("Snowball :",snow_stemmer.stem(w))
    print("Lancaster :",lan.stem(w))
    print("-----------------")
    print()
    time.sleep(1)

Original : Write
porter : write
Snowball : write
Lancaster : writ
-----------------

Original : Writing
porter : write
Snowball : write
Lancaster : writ
-----------------

Original : Writes
porter : write
Snowball : write
Lancaster : writ
-----------------

Original : Written
porter : written
Snowball : written
Lancaster : writ
-----------------

Original : ride
porter : ride
Snowball : ride
Lancaster : rid
-----------------

Original : riding
porter : ride
Snowball : ride
Lancaster : rid
-----------------

Original : rides
porter : ride
Snowball : ride
Lancaster : rid
-----------------

Original : rides
porter : ride
Snowball : ride
Lancaster : rid
-----------------

Original : run
porter : run
Snowball : run
Lancaster : run
-----------------

Original : runner
porter : runner
Snowball : runner
Lancaster : run
-----------------

Original : runs
porter : run
Snowball : run
Lancaster : run
-----------------

Original : running
porter : run
Snowball : run
Lancaster : run
----------------

## lemmatization

In [ ]:
import nltk

In [ ]:
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...


True

In [ ]:
lemma=nltk.WordNetLemmatizer()

In [ ]:
lemma.lemmatize("words")

'word'

In [ ]:
lemma.lemmatize("working")

'working'

In [ ]:
for w in words:
    print("Original :",w)
    print("porter :",pstem.stem(w))
    print("Snowball :",snow_stemmer.stem(w))
    print("Lancaster :",lan.stem(w))
    print("Lemmatize :",lemma.lemmatize(w))
    print("-----------------")
    print()
    time.sleep(1)

Original : Write
porter : write
Snowball : write
Lancaster : writ
Lemmatize : Write
-----------------

Original : Writing
porter : write
Snowball : write
Lancaster : writ
Lemmatize : Writing
-----------------

Original : Writes
porter : write
Snowball : write
Lancaster : writ
Lemmatize : Writes
-----------------

Original : Written
porter : written
Snowball : written
Lancaster : writ
Lemmatize : Written
-----------------

Original : ride
porter : ride
Snowball : ride
Lancaster : rid
Lemmatize : ride
-----------------

Original : riding
porter : ride
Snowball : ride
Lancaster : rid
Lemmatize : riding
-----------------

Original : rides
porter : ride
Snowball : ride
Lancaster : rid
Lemmatize : ride
-----------------

Original : rides
porter : ride
Snowball : ride
Lancaster : rid
Lemmatize : ride
-----------------

Original : run
porter : run
Snowball : run
Lancaster : run
Lemmatize : run
-----------------

Original : runner
porter : runner
Snowball : runner
Lancaster : run
Lemmatize : ru

## spell correction

### Text Blob

In [ ]:
!pip install -q textblob


[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
from textblob import TextBlob

In [ ]:
sent1="Python is neww ggeneration programing language"

In [ ]:
sent1

'Python is neww ggeneration programing language'

In [ ]:
sent_blob=TextBlob(sent1)

In [ ]:
sent_blob

TextBlob("Python is neww ggeneration programing language")

In [ ]:
sent_blob.correct()

TextBlob("Python is new generation programming language")

In [ ]:
sent2="Shee go to school everydy"

In [ ]:
sent2_blob=TextBlob(sent2)

In [ ]:
sent2_blob.correct()

TextBlob("Thee go to school everyday")

## pySpellChecker

In [ ]:
!pip install pyspellchecker

   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/7.2 MB 4.2 MB/s eta 0:00:02
   -------- ------------------------------- 1.6/7.2 MB 4.2 MB/s eta 0:00:02
   --------------- ------------------------ 2.9/7.2 MB 4.9 MB/s eta 0:00:01
   --------------------- ------------------ 3.9/7.2 MB 5.1 MB/s eta 0:00:01
   ---------------------------- ----------- 5.2/7.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------- ----- 6.3/7.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 5.1 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import spellchecker

In [ ]:
from spellchecker import SpellChecker

In [ ]:
spell=SpellChecker()

In [ ]:
sent1='Pyton is neww ggeneration programing language'

In [ ]:
sent1

'Pyton is neww ggeneration programing language'

In [ ]:
for w in sent1.split():
    print(w)

Pyton
is
neww
ggeneration
programing
language


In [ ]:
for w in sent1.split():
    print(w)
    r=spell.correction(word=w)
    print(r)

Pyton
python
is
is
neww
new
ggeneration
generation
programing
programing
language
language


In [ ]:
wlist=[]
for w in sent1.split():
    print(w)
    r=spell.correction(word=w)
    wlist.append(r)
res=" ".join(wlist)
print(res)    

Pyton
is
neww
ggeneration
programing
language
python is new generation programing language


In [ ]:
sent2

'Shee go to school everydy'

In [ ]:
for w in sent2.split():
    print(w)
    r=spell.correction(w)
    print(r)
    print()

Shee
she

go
go

to
to

school
school

everydy
everyday



## Embedding

In [ ]:
pip install -q gensim

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import gensim

In [ ]:
import gensim.downloader as api

In [ ]:
wv_model=api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
wv_model

In [ ]:
wv_model["king"]

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [ ]:
len(wv_model["king"])

300

In [ ]:
wv_model["queen"]

array([ 0.00524902, -0.14355469, -0.06933594,  0.12353516,  0.13183594,
       -0.08886719, -0.07128906, -0.21679688, -0.19726562,  0.05566406,
       -0.07568359, -0.38085938,  0.10400391, -0.00081635,  0.1328125 ,
        0.11279297,  0.07275391, -0.046875  ,  0.06591797,  0.09423828,
        0.19042969,  0.13671875, -0.23632812, -0.11865234,  0.06542969,
       -0.05322266, -0.30859375,  0.09179688,  0.18847656, -0.16699219,
       -0.15625   , -0.13085938, -0.08251953,  0.21289062, -0.35546875,
       -0.13183594,  0.09619141,  0.26367188, -0.09472656,  0.18359375,
        0.10693359, -0.41601562,  0.26953125, -0.02770996,  0.17578125,
       -0.11279297, -0.00411987,  0.14550781,  0.15625   ,  0.26757812,
       -0.01794434,  0.09863281,  0.05297852, -0.03125   , -0.16308594,
       -0.05810547, -0.34375   , -0.17285156,  0.11425781, -0.09033203,
        0.13476562,  0.27929688, -0.04980469,  0.12988281,  0.17578125,
       -0.22167969, -0.01190186,  0.140625  , -0.18164062,  0.11

In [ ]:
len(wv_model["queen"])

300

In [ ]:
wv_model["car"]

array([ 0.13085938,  0.00842285,  0.03344727, -0.05883789,  0.04003906,
       -0.14257812,  0.04931641, -0.16894531,  0.20898438,  0.11962891,
        0.18066406, -0.25      , -0.10400391, -0.10742188, -0.01879883,
        0.05200195, -0.00216675,  0.06445312,  0.14453125, -0.04541016,
        0.16113281, -0.01611328, -0.03088379,  0.08447266,  0.16210938,
        0.04467773, -0.15527344,  0.25390625,  0.33984375,  0.00756836,
       -0.25585938, -0.01733398, -0.03295898,  0.16308594, -0.12597656,
       -0.09912109,  0.16503906,  0.06884766, -0.18945312,  0.02832031,
       -0.0534668 , -0.03063965,  0.11083984,  0.24121094, -0.234375  ,
        0.12353516, -0.00294495,  0.1484375 ,  0.33203125,  0.05249023,
       -0.20019531,  0.37695312,  0.12255859,  0.11425781, -0.17675781,
        0.10009766,  0.0030365 ,  0.26757812,  0.20117188,  0.03710938,
        0.11083984, -0.09814453, -0.3125    ,  0.03515625,  0.02832031,
        0.26171875, -0.08642578, -0.02258301, -0.05834961, -0.00

In [ ]:
len(wv_model["car"])

300

In [ ]:
wv_model["teacher"]

array([ 2.63671875e-01, -1.61132812e-01,  1.07910156e-01,  1.44531250e-01,
        3.46679688e-02,  1.72851562e-01,  2.63671875e-01, -1.60156250e-01,
        2.58789062e-02, -8.34960938e-02,  2.92968750e-01, -4.71191406e-02,
       -1.57226562e-01, -2.65625000e-01,  5.32226562e-02,  3.26171875e-01,
       -2.91748047e-02, -5.95703125e-02,  8.64257812e-02, -3.22265625e-01,
        1.75781250e-01,  1.35742188e-01,  2.73437500e-02,  3.75976562e-02,
        1.32812500e-01, -5.46875000e-01,  2.80380249e-04, -6.98242188e-02,
        3.27148438e-02, -1.42822266e-02,  1.30859375e-01, -1.31835938e-01,
       -1.76757812e-01,  1.43554688e-01, -1.76757812e-01, -1.84570312e-01,
        3.90625000e-01,  3.14453125e-01,  8.78906250e-02,  2.96630859e-02,
       -1.89453125e-01, -1.16699219e-01,  1.42578125e-01, -1.07421875e-01,
        5.61523438e-02, -1.87988281e-02,  1.44531250e-01,  6.64062500e-02,
       -1.06445312e-01,  1.01074219e-01, -3.84765625e-01, -1.72851562e-01,
       -1.95312500e-02, -

In [ ]:
len(wv_model["teacher"])

300

In [ ]:
wv_model.most_similar("teacher",topn=10)

[('teachers', 0.7434303164482117),
 ('Teacher', 0.7094013690948486),
 ('guidance_counselor', 0.6960431933403015),
 ('elementary', 0.6790565252304077),
 ('PE_teacher', 0.6539358496665955),
 ('schoolteacher', 0.6529020071029663),
 ('school', 0.6382405757904053),
 ('pupil', 0.6304073929786682),
 ('student', 0.6301365494728088),
 ('paraprofessional', 0.625108003616333)]

In [ ]:
wv_model.most_similar("hospital",topn=5)

[('Hospital', 0.7931912541389465),
 ('hopsital', 0.7784007787704468),
 ('hosptial', 0.7581779956817627),
 ('hospitals', 0.7212538123130798),
 ('intensive_care', 0.720590353012085)]

In [ ]:
wv_model.similarity("school","teacher")

np.float32(0.6382406)

In [ ]:
wv_model.similarity("nurse","doctor")

np.float32(0.63195235)

In [ ]:
wv_model.similarity("king","queen")

np.float32(0.6510957)

In [ ]:
wv_model["man"]

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [ ]:
wv_model["woman"]

array([ 2.43164062e-01, -7.71484375e-02, -1.03027344e-01, -1.07421875e-01,
        1.18164062e-01, -1.07421875e-01, -1.14257812e-01,  2.56347656e-02,
        1.11816406e-01,  4.85839844e-02, -9.71679688e-02, -3.43750000e-01,
       -6.29882812e-02, -1.25000000e-01, -2.70996094e-02,  9.42382812e-02,
       -1.87500000e-01, -5.34667969e-02,  6.25000000e-02, -3.05175781e-02,
       -2.90527344e-02, -4.80957031e-02, -5.51757812e-02, -4.08203125e-01,
        1.01318359e-02, -2.32421875e-01, -1.70898438e-01,  2.63671875e-01,
        3.49609375e-01, -2.11914062e-01,  1.43554688e-01, -6.22558594e-03,
       -2.25585938e-01, -1.05468750e-01, -1.16210938e-01,  1.23046875e-01,
        3.06640625e-01, -4.88281250e-02, -9.57031250e-02,  1.99218750e-01,
       -1.57226562e-01, -2.80761719e-02,  1.58203125e-01, -2.42919922e-02,
        1.29882812e-01, -8.98437500e-02, -7.61718750e-02,  3.54003906e-02,
       -3.06396484e-02,  1.52343750e-01,  5.24902344e-02,  1.60980225e-03,
        5.56640625e-02,  

In [ ]:
res=wv_model["king"]-wv_model["man"]

In [ ]:
final=res+wv_model["woman"]

In [ ]:
wv_model.most_similar(final)

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

#positive==king+woman
#negetive==man

In [ ]:
wv_model.most_similar(positive=["king","woman"],negative=["man"])

[('queen', 0.7118193507194519),
 ('monarch', 0.6189674139022827),
 ('princess', 0.5902431011199951),
 ('crown_prince', 0.5499460697174072),
 ('prince', 0.5377321839332581),
 ('kings', 0.5236844420433044),
 ('Queen_Consort', 0.5235945582389832),
 ('queens', 0.518113374710083),
 ('sultan', 0.5098593235015869),
 ('monarchy', 0.5087411403656006)]